### ISSUE TITLE
Release version based on typescript-eslint 8.0.0 beta

### ISSUE THREAD

**Issue by voxpelli** [eslint-stylistic/eslint-stylistic#414]
Since `typescript-eslint` throws peer-dependency errors unless one uses the `8.0.0` beta it would be great to get a (pre-)release of eslint-stylistic that uses that version: https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta

I'm running into peer dependency issues in the [`neostandard`](https://github.com/neostandard/neostandard) config where I use the `8.0.0` beta but eslint stylistic pulls in the `7.x` version

**Comment by antfu** [comment]
I don't think we should bump to a pre-release in our dependencies now, as not every user wants to opt-in for the beta versions, and we shouldn't enforce them.

I would wait until they do stable releases. For now you can always use your local package resolutions/overrides to ensure you have a single version of ts-eslint packages.

**Comment by voxpelli** [comment]
@antfu The problem is that those of us who are relying on ESLint 9 currently gets lots of `unmet peer dependency` when using `@stylistic`: https://github.com/neostandard/neostandard/issues/35

Would it be possible to move to a peer dependency setup where `@stylistic` accepts both 7.x and 8.0.0 prereleases

**Comment by voxpelli** [comment]
Our solution was to simply remove stylistic TS rules for now and only have stylistic rules for JS

**Comment by jerome-benoit** [comment]
> @antfu The problem is that those of us who are relying on ESLint 9 currently gets lots of `unmet peer dependency` when using `@stylistic`: [neostandard/neostandard#35](https://github.com/neostandard/neostandard/issues/35)

It's more than just unmet dependencies message, TS code is not properly handled at all: formatting is incorrect, rules needing types checking misbehave, ... Having the two different major typescript-eslint version installed result in global linter misbehavior, including plugins using typescript-eslint API.

**Comment by antfu** [comment]
Just mention again you can override your local version with your package manager:

- https://pnpm.io/package_json#pnpmoverrides
- https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by jerome-benoit** [comment]
> Just mention again you can override your local version with your package manager:
> 
> * https://pnpm.io/package_json#pnpmoverrides
> * https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

It's not an acceptable solution for an all-in-one dep targeting at enforcing standard coding style in TS, JS, ... code base to require package manager tuning to work properly on TS code base. Since at some point in time, [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) will support typescript-eslint 8, I guess the neostandard maintainers have decided to wait for it before reintegrating TS code base formatting.

**Comment by antfu** [comment]
It's not we are requiring you to do it - it's the fact that typescript-eslint v8 is just **not out yet**. It's not practical for a stable package to ship a beta dependencies, if you decided to use the beta anyway, you take care the logicisic. Otherwise you might wait, we will bump the deps as soon as the ts-eslint v8 stable comes out.

**Comment by jerome-benoit** [comment]
It's fine. 

But given the outcomes with two different major typescript-eslint version installed: 

- a big fat warning should be issued in that case about misbehavior => typescript-eslint upstream bug report
- [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) can consider shipping alpha releases with typescript-eslint 8 support only in order to allow its support stabilization. That version will be a breaking change and it looks like to be not trivial.

**Comment by jerome-benoit** [comment]
> It feels wrong that my JavaScript project using stylistic has anything do to with TypeScript versioning.

It's because of "@typescript-eslint/utils": "^7.12.0" dep in several sub-packages package.json. I have no clue on its requirement since I do not know the code base. But I agree: a formatting only eslint plugin should not rely on typescript-eslint plugin to format TS files. 

Maybe: 

- Untangle typescript-eslint requirement in existing rules when possible: split rules needing it from rules not 
- Detect if typescript-eslint is installed with a supported version as external dep and then enable optional rules requiring it

**Comment by voxpelli** [comment]
> it's not practical for a stable package to ship a beta dependencies

What I was asking for is to make a pre-release of your own rather than wait for typescript-eslint 8.x to ship.

That way you will help out validate the new version, ensure no regressions remains in the stable version etc.

On top of that the typescript-eslint 8.x version is special, as unlike ESLint 9 the typescript-eslint crew decided to remove all style rules in 8.x, not just have them deprecated, leaving users of style rules with little way to test out the typescript-eslint 8.x release unless eslint-stylistic helps out.

**Comment by antfu** [comment]
I see. I am convinced. We will do beta releases with ts-eslint v8 then
